### PR TITLE
Update/project fixes

### PR DESCRIPTION
**Pull request by suejinkim20**

### CODE REVIEW

**Review by mbwatson — COMMENTED** [review]
i wonder if we should skip the markdown processing in the project cards. for example, the two projects on the far left and far right sides in this screenshot don't feel quite right, with the bulleted list and external link rendering.

Screenshot from 2023-03-14 13-15-48

what do you think?

**Comment by suejinkim20** [comment]
> i wonder if we should skip the markdown processing in the project cards. for example, the two projects on the far left and far right sides in this screenshot don't feel quite right, with the bulleted list and external link rendering.
> 
> Screenshot from 2023-03-14 13-15-48
> 
> what do you think?

I agree with you, Matt. My first choice to address this issue would be to have a separate, additional "excerpt" field that only accepts text (no rich-text). And, this part might be overkill, but maybe require the field, as well as add minimum and maximum character limits. I think, even if we just implemented the first part, it would help to ensure that each project is presented cleanly, and still maintain the way that their description looks on their individual project pages.

This might be a moot point if we end up changing the look and layout of the projects page (which I am anticipating will be the case). But, I still think it will help make sure the spotlight component on the home page looks good.

**Comment by mbwatson** [comment]
that seems like a good approach, but adding an extra field and populating it for all the projects would be a rather large lift. it's worth looking for an intermediate solution. perhaps we could extract the text only and lose the markdown formatting.

it looks like this [remark plugin](https://github.com/remarkjs/strip-markdown) does just that. alternatively, i could envision accomplishing this same thing with a specialized, card-specific version of our markdown component that turns all nodes into `span`s, for example.

**Comment by mbwatson** [comment]
this branch crashes with the following error for me:

```
error - Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**Review by mbwatson — APPROVED** [review]
looks good. this is a great way to reduce the incoming HTML to just text. i see what you mean about the lists, though; it does look like there's room to add delimeters to make a list easier to read, but we shouldn't let that hold up this PR, especially considering i haven't seen on show up early enough in the description to get rendered in the project cards.

so, :+1:

**Pull request merged**
