### PR TITLE
Article Routes

### PR DESCRIPTION
**Pull request by Woozl**
This initial template for the individual article pages. These should be generated at build time or incrementally generated with [ISR](https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration). I have set up the initial fetching for each page, the routes look like this to the user:

```
/news/2023/11/13/article-title-as-slug
```

Currently this is done using a [catch-all route](https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes#catch-all-segments) and not using the first three route segments (the date). However, I'd like the user to be able to visit a route for each day/month/year and view a list of articles:

image

I'm currently still trying to determine the best way to add this functionality:
1. building this functionality into the catch-all and conditionally rendering the UI based on if it's a grouping page or an article page
2. having nested dynamic routes (i.e., nested folders in the pages directory) and managing the different UIs in each file (potentially with a shared layout component for the group types of year, month, and day).

### CODE REVIEW

**Comment by Woozl** [comment]
After exploring both options, using the nested dynamic routes seems more flexible. I have added a `TimeGrouping` UI component (`components/news/time-grouping.js`) to be used in `[year]/index.js`, `[month]/index.js`, and `[day]/index.js`, so that logic isn't repeated.

image

**Review by suejinkim20 — APPROVED** [review]
looks great!

**Comment by Woozl** [comment]
Here are some good example articles:

Multiple images: http://localhost:3000/news/2023/6/5/renci-strengthens-storm-surge-response-capabilities
Subtitle, rich markdown: http://localhost:3000/news/2023/7/11/data-matters-short-course-series-returns-in-august-2023
A lot of tagged items: http://localhost:3000/news/2022/1/31/drone-projects-take-data-processing-and-communication-to-new-heights

Couple things @suejinkim20 or I noticed:
- some of the really long tags overflow on small screens (I attempted fixing this, but the wrapping `<a>` tag seems to mess up the `text-overflow: ellipsis` css)
- We need to get subtitles under the images
- some spacing and general layout fixes

**Comment by Woozl** [comment]
However, I'm going to go ahead and merge this and create the appropriate issues.

**Pull request merged**
