### PR TITLE
Feature/link tray

### PR DESCRIPTION
**Pull request by suejinkim20**

### CODE REVIEW

**Review by mbwatson — CHANGES_REQUESTED** [review]
works great; good job! a few things--

1. we'll want those links to always open in a new tab. let's just run those through our Link component or hardcode the target
2. we should probably give in to the fact that Twitter is X now

**Review by mbwatson — APPROVED** [review]
works and looks great! are we boycotting the X logo :smile:?

**Comment by suejinkim20** [comment]
@mbwatson I was having trouble implementing our custom link component with the icon button (comment 1) but i will go ahead and update the X/twitter logo (comment 2) 😅

**Review by mbwatson — APPROVED** [review]
:+1: looks good to me

**Review by Woozl — CHANGES_REQUESTED** [review]
~~I'm getting this error on the ncds page (http://localhost:3000/collaborations/ncds):~~

Disregard this, the error was the missing update X logo since I forgot to `npm i`.

**Review by Woozl — APPROVED** [review]

**Pull request merged**
